### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by arisdnt** [manulthanura/Positivus#12]
can you help me to fix the navbar problem?
![menu](https://github.com/user-attachments/assets/b11453dc-a481-4fea-bea7-1868bb8df64b)

**Comment by manulthanura** [comment]
Yes, I can help with that. It looks like you're viewing the website within a width range of 770px to 1014px. Can you provide more details about the specific issue you're experiencing with the navbar?

**Comment by arisdnt** [comment]
I'm having trouble explaining, I'll send you a screen recording

https://github.com/user-attachments/assets/ec0f6e91-3d78-494b-aa89-57045e1c3752

**Comment by arisdnt** [comment]
I'm having trouble explaining, I'll send you a screen recording

Uploading bandicam 2024-09-13 17-34-28-502.mp4…

**Comment by arisdnt** [comment]
I'm having trouble explaining, I'll send you a screen recording

https://github.com/user-attachments/assets/cde206d8-98bc-45a1-aad8-c467db1b50ae

**Comment by manulthanura** [comment]
I made a PR, Please check your issue is solved
